### ISSUE TITLE
Leftover awslogs launcher PID causing failure to start awslogs

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/packer-aem#192] opened 2019-10-30 05:35 UTC
We have noticed that awslogs intermittently fails to start on environment creation step due to the launcher PID file not getting removed before the AMI is created. It's suspected that perhaps awslogs hasn't been gracefully shut down completely before the EC2 instance is stopped.

Rather than relying on an implicit stop, we need to introduce a step to stop awslogs, and then wait for the PID file is removed. We should also add an InSpec check that the PID file is no longer there.

**Comment by mbloch1986** [comment] 2019-11-13 23:48
In order to this we also need to prevent the awslogs from the restarting, as the cronjob would attempt to restart the service. Furtheron we need to enable and start the awslogs service during provisioning.

**Comment by mbloch1986** [comment] 2019-11-14 01:34
I did a bit of a further investigation because I had the following behaviour on a few systems today:

* Provisioning successful
* /var/log/messages contains messages of stopping/starting awslogs service every minute... this came from the awslogs cronjob
* awslogs service is still not running ... even after the cronjob tries to restart it every minute...

The directory `/var/awslogs/state` contained the following files:

```
-rw-r--r--. 1 root root 12288 Nov 14 11:26 agent-state
-rw-r--r--. 1 root root     0 Nov 13 12:07 awslogs.lock
-rw-r--r--. 1 root root     4 Nov 13 12:07 awslogs.pid
-rw-r--r--. 1 root root   508 Sep 23 22:29 generated-files
```

Important is the `awslogs.lock` & `awslogs.pid`.

Cron job script code:
```
# Version: 1.4.3
PIDFILE=/var/awslogs/state/awslogs.pid
LOCKFILE=/var/awslogs/state/awslogs.lock

# Bail out if PID file doesn't exist. It implies that the
# process was never started.
if [ ! -f $PIDFILE ]
then
    exit 0
fi

/usr/bin/ps -C -p `/usr/bin/cat $PIDFILE` | /usr/bin/grep "/var/awslogs/bin/awslogs-agent-launcher.sh" > /dev/null
RETVAL=$?
echo
[ $RETVAL != 0 ] && [ -f $LOCKFILE ] && /usr/sbin/service awslogs restart

```

The CronJob checks first if the `PIDFILE` exists or not if not than it exits it, because it doesn't start a process which was stopped via `systemctl stop awslogs` @cliffano, this is weird isn't it ? Our experience is even though you stop it the cron job still attempt to restart the process. That's why we ended up with the workaround implementation for disabling the cronjobs

https://github.com/shinesolutions/aem-aws-stack-provisioner/blob/master/manifests/publish.pp#L53

... anyway.... If the Pidfile exists but the process isn't running with this pid the cron job only attempts a restart if also the `LOCKFILE(/var/awslogs/state/awslogs.lock)` exists. Both the case therefore it restarts the process. 

Now even though the restart get's triggered something is still preventing the restart of the process, as a `ps -ef | grep -i awslogs` doesn't show that the awslogs service is running. 

So far my investigations. I'll do some further investigations once I can reproduce it... Haven't said that all this is with the previous version of the awslogs agent `1.4.3`. We should use the latest version `1.4.6` and check if this is still happening.

**Comment by mbloch1986** [comment] 2019-11-14 02:13
I think what I wanted to say is that a stop of the awslogs service should be sufficient enough, we don't need to cleanup the pid file but we should check if the `/var/awslogs/state/awslogs.lock` was removed.

Furthermore do we also want to disable the awslogs service at the end of the baking and enable and start it during provisioning ? 

The reason for this is because we are stopping it on the publish instance before attaching the snapshot, we could update the publish provisioning to not stop and disable the awslogs service anymore as it's already done as part of the baking process. This also avoids the streaming of wrong AEM logs to cloudwatch / s3 ...

* 2nd Publish instance starts
* awslogs service starts
* awslogs service streams old AEM logs to cloudwatch
* Stopping awslogs service 
* attaching new AEM Volume
* awslogs service streams new AEM logs to cloudwatch

Also we don't need to restart the awslogs service on all other components, as part of updating the awslogs configuration file.

Pro:
* Increase provisioning time, as we don't have to restart awslog 
* Avoid streaming of wrong datas to cloudwatch

Con:
* Cloudwatchlogs might not be available for debugging provisioning errors

**Comment by mbloch1986** [comment] 2019-11-14 04:21
After doing some further investigation I was able to reproduce the issue 

I think the solution is to stop properly during the baking process.

How to reproduce:

* Login to an instance were the awslogs service isn't running
```
# grep awslogs /var/log/messages
[...]
# ps -ef |grep -i awslogs
[..]
```
You see that the awslogs service gets restarted every minute in the /var/log/messages but no process is actually running.

If so follow the following procedure:

1. Check the process id of the awslogs service
```
# cat /var/awslogs/state/awslogs.pid
494
```

2. Try to start the service manually
```
# . /etc/init.d/functions
# export PIDFILE=/var/awslogs/state/awslogs.pid
# export DAEMON_USER=root
# export DAEMON=/var/awslogs/bin/awslogs-agent-launcher.sh
# daemon --pidfile $PIDFILE --user=$DAEMON_USER "nohup $DAEMON &"
```

3. Verify that the service is not running
```
# ps -ef |grep -i awslogs
[..]
```

4. Increase number in the pid file + 1 & start service 
```
# echo 495 > /var/awslogs/state/awslogs.pid

# . /etc/init.d/functions
# export PIDFILE=/var/awslogs/state/awslogs.pid
# export DAEMON_USER=root
# export DAEMON=/var/awslogs/bin/awslogs-agent-launcher.sh
# daemon --pidfile $PIDFILE --user=$DAEMON_USER "nohup $DAEMON &"
# ps -ef | grep -i awslogs
# cat /var/awslogs/state/awslogs.pid
!!!NEW PID ID  !!!
```
You should see that the service is now running and that the pid file was updated. If so kill the service

```
kill $(cat /var/awslogs/state/awslogs.pid)
```

4. Decrease number in the pid file - 2 & start service 
```
# echo 493 > /var/awslogs/state/awslogs.pid

# . /etc/init.d/functions
# export PIDFILE=/var/awslogs/state/awslogs.pid
# export DAEMON_USER=root
# export DAEMON=/var/awslogs/bin/awslogs-agent-launcher.sh
# daemon --pidfile $PIDFILE --user=$DAEMON_USER "nohup $DAEMON &"
# ps -ef | grep -i awslogs
```

Now if we set a PID id equal or lower to the original PID id of 494 we see that systemd does not start the service it doesn't even execute the shell script `/var/awslogs/bin/awslogs-agent-launcher.sh`. I guess this is because of some internal behavviour of systemd when a service doesn't get properly stopped during OS shutdown. 

How To fix:

* Stop the service via `systemctl` in the baking process

```
systemctl stop awslogs
```

Removing the pid file doesn't really seem to solve the problem

1. Delete PID file
2. Start Service
Service should be up and running
3. Stop Service
4. Update PID ID
```
# echo 494 > /var/awslogs/state/awslogs.pid
```
5 . Start Service
Service is not started


Not sure what's happening here but further investigation would take too much time.

**Comment by mbloch1986** [comment] 2019-11-15 00:10
There is even an easier way to reproduce it ....

* stop awslogs
* get a PID of an actual running process and update this PID in `/var/awslogs/state/awslogs.pid`
* start awslogs

You will see that the awslogs service is *not* running. I guess this is a systemd behaviour.

Solution:
* Make sure awslogs service is stopped at baking
* make sure the pidfile is removed

**Comment by mbloch1986** [comment] 2020-03-20 03:55
Fixed in the latest packer-aem version.

**Closed by mbloch1986** 2020-03-20 03:55 UTC
Labels: bug, enhancement
